BugVote/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from api import views

import api.urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(api.urls)),

]

api/urls.py
from BugVote import settings
from api import views, urls_restful

__author__ = 'hason'

from django.conf.urls import url, include

urlpatterns = [
    url(r"m/(?P<path>.*)$", "django.views.static.serve", {"document_root": settings.MEDIA_ROOT}),
    url(r'^$', views.index_view),
    url(r"^api/", include(urls_restful)),
    url(r"^register/$", views.register_view),
    url(r"^login/$", views.login_view),
    url(r"^submit/$", views.submit_view),
    url(r"^person/$", views.person_view),
    url(r"^news/(?P<pk>\d+)/$", views.news_view),
    url(r"^rank_list/$", views.rank_list_view),
    url(r"^news_list/$", views.news_list_view),
    # 后台界面
    url(r"^manage/$", views.manage_view),
    url(r"^manage/user_list/$", views.manage_user_list),
    url(r"^manage/rank_list/$", views.manage_rank_list),
    url(r"^manage/bug_list/$", views.manage_bug_list),
    url(r"^manage/news_list/$", views.manage_news_list),
    url(r"^manage/system_setting/$", views.manage_system_setting),
    url(r"^manage/post_news/$", views.manage_post_news),
    url(r"^manage/check_news/$", views.manage_check_news),

]

api/models.py
from django.db import models


class Administration(models.Model):
    username = models.CharField(max_length=20, unique=True)
    password = models.CharField(max_length=40)

    def __str__(self):
        return self.username


class ImageItem(models.Model):
    image = models.ImageField(upload_to="images/")
    desc = models.TextField(blank=True, default="#")


class BugType(models.Model):
    name = models.CharField(max_length=30, unique=True)

    def __str__(self):
        return self.name


class Config(models.Model):
    name = models.CharField(max_length=40, unique=True)
    context = models.TextField(blank=True, default="")
    images = models.ManyToManyField(ImageItem, blank=True)

    def __str__(self):
        return self.name


class User(models.Model):
    phone_number = models.CharField(max_length=11, primary_key=True)
    password = models.CharField(max_length=40)
    school = models.CharField(max_length=40)
    major = models.CharField(max_length=40)
    name = models.CharField(max_length=30)
    email = models.EmailField()
    address = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    bug_number = models.PositiveIntegerField(default=0)
    bonus = models.PositiveIntegerField(default=0)
    rank = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.name + " " + self.phone_number


class BugRecord(models.Model):
    commit_person = models.ForeignKey(User)
    information = models.TextField()
    bonus = models.PositiveIntegerField(default=0)
    bug_type = models.ForeignKey(BugType)
    have_seen = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)


class News(models.Model):
    title = models.TextField()
    author = models.CharField(max_length=40)
    time = models.DateTimeField(auto_now_add=True)
    context = models.TextField()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('-time',)

templates/footer.html
<footer class="footer ">
    <div class="container">
        <div class="row footer-top">
            <div class="col-sm-6 col-lg-6">
                <h4>
                    活动图片Logo
                </h4>

                <p>主办单位：北京良润天下信息技术有限公司</p>

                <p>承办单位：吉林大学</p>

                <p>联系电话：188****8871</p>
            </div>
            <div class="col-sm-6  col-lg-5 col-lg-offset-1">
                <div class="row about">
                    <div class="col-xs-3">
                        <h4>关于</h4>
                        <ul class="list-unstyled">
                            <li><a href="/about/">关于我们</a></li>
                            <li><a href="/ad/">广告合作</a></li>
                            <li><a href="/links/">友情链接</a></li>
                            <li><a href="/hr/">招聘</a></li>
                        </ul>
                    </div>
                    <div class="col-xs-3">
                        <h4>联系方式</h4>
                        <ul class="list-unstyled">
                            <li><a href="http://weibo.com/bootcss" title="Bootstrap中文网官方微博" target="_blank">新浪微博</a>
                            </li>
                            <li><a href="mailto:admin@bootcss.com">电子邮件</a></li>
                        </ul>
                    </div>
                    <div class="col-xs-3">
                        <h4>旗下网站</h4>
                        <ul class="list-unstyled">
                            <li><a href="http://www.golaravel.com/" target="_blank">Laravel中文网</a></li>
                            <li><a href="http://www.ghostchina.com/" target="_blank">Ghost中国</a></li>
                        </ul>
                    </div>
                    <div class="col-xs-3">
                        <h4>赞助商</h4>
                        <ul class="list-unstyled">
                            <li><a href="http://www.ucloud.cn/" target="_blank">UCloud</a></li>
                            <li><a href="https://www.upyun.com" target="_blank">又拍云</a></li>
                        </ul>
                    </div>
                </div>

            </div>
        </div>
        <hr/>
        <div class="row footer-bottom">
            <ul class="list-inline text-center">
                <li><a href="http://www.miibeian.gov.cn/" target="_blank">京ICP备11008151号</a></li>
                <li>京公网安备11010802014853</li>
            </ul>
        </div>
    </div>
</footer>

templates/head.html
{% load staticfiles %}

<nav class="navbar navbar-inverse">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"><img alt="" width="30"
                                                  src="{% static 'bug_vote/image/logo.png' %}"></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">首页</a></li>
                <li><a href="/submit/">我要提交</a></li>
                <li><a href="/rank_list/">比赛排名</a></li>
                <li><a href="/news_list/">赛事动态</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">

                {% if name %}
                    <li><a href="/person/" style="color: #337ab7;"><strong><span
                            id="head_name"> {{ name }}</span></strong></a></li>
                    <li><a href="javascript:logout_ajax()">注销</a></li>
                {% else %}
                    <li><a href="/login/">登录</a></li>
                    <li><a href="/register/">注册</a></li>
                {% endif %}
            </ul>

        </div>
        <!--/.nav-collapse -->
        {% if name %}
            <script>
                function logout_ajax() {
                    var xmlhttp = new XMLHttpRequest();
                    xmlhttp.open("GET", "/api/log_out/", false);
                    xmlhttp.send();
                    location.reload()
                }
            </script>
        {% endif %}
    </div>
</nav>

templates/html_head.html
{% load staticfiles %}

<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
<meta name="renderer" content="webkit">
<meta name="description" content="Voting-Program">
<meta name="author" content="QJX">
<link rel="icon" href="{% static 'bug_vote/image/icon.jpeg' %}" type="image/x-icon"/>
<link rel="shortcut icon" href="{% static 'bug_vote/image/icon.jpeg' %}" type="image/x-icon"/>

<!-- Bootstrap core CSS -->
<link href="{% static 'bug_vote/css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'bug_vote/css/mycss.css' %}" rel="stylesheet">

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
      <script src="//cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="//cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

templates/index.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    {% load staticfiles %}
    <title>Bug投票大赛</title>
    {% include "html_head.html" %}
</head>
<body>
{% include "head.html" %}

<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        {% for index in pic_index %}
            <li data-target="#carousel-example-generic" data-slide-to="{{ index }}" {% ifequal pic_index|first index %}
                class="active" {% endifequal %}></li>
        {% endfor %}
    </ol>

    <div class="carousel-inner" role="listbox">
        {% for pic in pic_list %}
            <div class="item {% ifequal pic_list|first pic %} active {% endifequal %}">
                <a href="{{ pic.desc }}"> <img src="{{ pic.image.url }}" alt="加载错误">
                </a>
            </div>
        {% endfor %}
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>


<div class="container">
    <div class="col-xs-12 col-sm-9">

        <div class="page-header">
            <h1>比赛排名</h1>
        </div>
        <table class="table table-hover table-striped">
            <thead>
            <tr>
                <th>名次</th>
                <th>名字</th>
                <th>学校</th>
                <th>获得奖金数</th>
                <th>Bug数量</th>
            </tr>
            </thead>

            <tbody>
            {% for i,rank in rank_list.items %}
                <tr>
                    <td>{{ i }}</td>
                    <td>{{ rank.name }}</td>
                    <td>{{ rank.school }}</td>
                    <td>{{ rank.bonus }}</td>
                    <td>{{ rank.bug_number }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <p style="float:right"><a class="btn btn-default" href="/rank_list/" role="button">查看全部 &raquo;</a></p>

        <div class="page-header" style="padding-top: 40px">
            <h1>赛事动态</h1>
        </div>

        <div class="list-group">
            {% for news in news_list %}
                <a href="/news/{{ news.id }}/" class="list-group-item " style="border: 0">
                    <h3 class="list-group-item-heading">{{ news.title }}
                    </h3>

                    <p></p>

                    <p class="list-group-item-text text-muted">
                        <small>发布时间：{{ news.time }}</small>
                    </p>
                </a>
                <hr/>

            {% empty %}
                <a class="list-group-item " style="border: 0">
                    <h3 class="list-group-item-heading">暂时没有新闻
                    </h3>

                    <p></p>

                </a>
                <hr/>
            {% endfor %}


        </div>

        <p style="float:right"><a class="btn btn-default" href="/news_list/" role="button">查看全部 &raquo;</a></p>

    </div>


    <div class="col-xs-12 col-sm-3" id="sidebar">
        <div class="row" style="padding: 15px">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">倒计时</h3>
                </div>
                <div class="panel-body h2 text-center">
                    {{ last_days }}
                </div>
            </div>
        </div>

        <div class="list-group text-center">
            <a href="/submit/" class="list-group-item ">
                <h4 class="list-group-item-heading" style="padding: 15px 0">我要参加</h4>
                <!-- <p class="list-group-item-text">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p> -->
            </a>
        </div>

    </div>
</div>


{% include 'footer.html' %}

<script src="{% static 'bug_vote/js/jquery.min.js' %}"></script>
<script src="{% static 'bug_vote/js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    {% load staticfiles %}
        <title>登陆</title>

    {% include "html_head.html" %}
    <style>
        .navbar {
            margin-bottom: 0px;
            border-radius: 0px;
        }

        .jumbotron {
            height: 50px;
            /*background-attachment:fixed;*/
            background: no-repeat 0 -400px;
            background-size: 100%;
        }

        .reg-box {
            width: 330px;
            border-radius: 10px;
            /*background-color: lightgrey;*/
        }

        .form-group {
            position: relative;
            padding: 6px;
        }

        .form-control {
            height: 40px;
        }

        .btn-success {
            height: 38px;
            padding: 8px;
        }

        /*      span {
                position: absolute;
                left: 400px;
                top: 15px;
              }*/
        .visible-xs {
            font-size: 40px;
            text-align: center;
        }

        .reg-head {
            width: 600px;
            padding: 30px 0;
            position: relative;

        }

        .register-font {
            font-size: 40px;
            text-align: center;
            position: absolute;
            left: 200px;
            top: 20px;
            width: 180px;
            background-color: #FFF;;
        }

        .suc-box {
            margin-top: 70px;
            text-align: center;
            width: 500px;
            height: 300px;
            background-color: lightgrey;
            /*border: 1px solid lightgrey;*/
            border-radius: 5px;
        }

        .suc-box h1 {
            margin: 70px;
        }

        .suc-box a {
            font-size: 15px;
        }

        .foot-box {
            margin-top: 40px;
            font-size: 15px;
            text-align: center;
            background: #F5F5F5 none repeat scroll 0% 0%;
            height: 70px;
            /*width:330px;*/
            line-height: 70px;
        }

        /*      .nav-pills > li > a{
                border-radius: 20px;
              }*/
    </style>
</head>
<body>
{% include "head.html" %}


<div class="container reg-head hidden-xs">
    <hr/>
    <p class="register-font">用户登录</p>
</div>


<div class="container reg-box">
    <form class="form" action="javascript:login_ajax()" method="post">
        <div class="visible-xs">
            <p>登录</p>
        </div>
        <div id="warn_msg" class="form-group alert alert-danger hide"></div>
        <div class="form-group">
            <input type="text" name="phone_number" class="form-control" placeholder="用户名（手机号）">
        </div>
        <div class="form-group">
            <input type="password" name="password" class="form-control" placeholder="密码">
        </div>

        <div class="form-group">
            <div style="display:inline-block">
                <div class="checkbox">
                    <label>
                        <input name="remember" type="checkbox" checked="checked"> 记住我
                    </label>
                    <a href="javascript:;" style="padding-left:10px">忘记密码</a>
                </div>
            </div>
            <button class="btn btn-success pull-right" type="submit" style="width: 40%;display:inline-block">登录</button>
        </div>

        <div class="foot-box">
            还没有账号？
            <a href="/register/">立即注册</a>
        </div>

    </form>
</div>


<script src="{% static 'bug_vote/js/jquery.min.js' %}"></script>
<script src="{% static  'bug_vote/js/csrf_ajax.js' %}"></script>
<script language="JavaScript">
    function login_ajax() {
        var phone = document.getElementsByName("phone_number")[0].value;
        var pass = document.getElementsByName("password")[0].value;
        var remember = document.getElementsByName("remember")[0].checked;
        $.post("/api/log_in/", {
                    phone_number: phone,
                    password: pass,
                    remember: remember
                }, function (result) {
                    if (result.is_success) {
                        location.href = "/";
                    } else {
                        var ele = $("#warn_msg");
                        ele.removeClass("hide");
                        ele.text(result.msg);
                    }
                }
        )
    }
</script>
{% include 'footer.html' %}

</body>
</html>

templates/news.html
<html lang="zh-CN">
<head>
    {% load staticfiles %}
    {% include 'html_head.html' %}
    <title> {{ news.title }} </title>
</head>
<body>
{% include 'head.html' %}
<div class="container">
    <div class="container col-sm-9">
        <h2 class="text-center">{{ news.title }}</h2>

        <p class="text-center">{{ news.author }} 发布时间：{{ news.time }}</p>
        <hr/>
        <div style="font-size: 18px; line-height: 30px">
            {% for line in news_content %}
                <p>{{ line }}</p>
            {% endfor %}

        </div>
    </div>

    <div class="container col-sm-3">
        <blockquote>新闻动态</blockquote>
        <ol class="list-group-item-text">
            {% for news_item in news_list %}
                <li><a href="/news/{{ news_item.id }}/">{{ news_item.title }}</a></li>
            {% endfor %}
        </ol>
    </div>
</div>

{% include 'footer.html' %}

</body>
</html>

templates/news_list.html
<html lang="zh-CN">
<head>
    {% load staticfiles %}
    {% include "html_head.html" %}
    <title>新闻动态</title>
<body>

{% include "head.html" %}

<div class="container">
    <div class="page-header" style="padding-top: 40px">
        <h1>新闻动态</h1>
    </div>

    <div class="list-group">
        {% for news in news_list %}
            <a href="/news/{{ news.id }}/" class="list-group-item " style="border: 0">
                <h3 class="list-group-item-heading">{{ news.title }}
                </h3>

                <p></p>

                <p class="list-group-item-text text-muted">
                    <small>发布时间：{{ news.time }}</small>
                </p>
            </a>
            <hr/>
        {% endfor %}


    </div>
</div>

{% include 'footer.html' %}
</body>
</html>

templates/pers.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    {% load staticfiles %}
    {% include 'html_head.html' %}
    <title>个人中心</title>
</head>
<body>
<!-- Fixed navbar -->
{% include "head.html" %}

<div class="container">
    <div class="page-header">
        <h1>个人中心</h1>
    </div>
    <div class="col-xs-12 col-sm-9" id="sidebar">
        {% for record in user.bugrecord_set.all %}
            <div class="panel panel-default">
                <div class="panel-heading" style="position: relative">
                    <h1 class="panel-title">{{ record.bug_type }}</h1>

                    <p style="display: inline-block;position: absolute;right: 50px;top: 10px">
                        提交时间：{{ record.created }}</p>
                </div>
                <div class="panel-body">
                    {{ record.information }}
                </div>
                <div class="panel-body">
                    {% ifequal record.bonus 0 %}
                        {% if record.have_seen %}
                            <button type="button" class="btn btn-danger pull-right"><strong>未通过</strong></button>
                        {% else %}
                            <button type="button" class="btn btn-warning pull-right"><strong>已提交</strong></button>
                        {% endif %}
                    {% else %}
                        <button type="button" class="btn btn-success pull-right">
                            <strong>已过审 {{ record.bonus }}￥</strong></button>

                    {% endifequal %}

                </div>
            </div>

        {% empty %}

            <div style="height: 400px;border-radius: 5px; background-color: #F5F5F5;text-align: center;padding-top: 150px">
                <h2>您还没有提交任何BUG~</h2>
                <a href="/submit/" style="font-size: 20px;margin-top: 30px">马上提交</a>
            </div>
        {% endfor %}


    </div>

    <div class="col-xs-12 col-sm-3">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h1 class="panel-title">
                    我的账户
                </h1>

            </div>
            <div class="panel-body">
                <p>账号：{{ user.phone_number }}</p>

                <P>BUG数：{{ user.bug_number }}</P>

                <p>奖金：{{ user.bonus }}</p>

                <p>排名：{% ifequal user.rank 0 %}未更新{% else %}{{ user.rank }}{% endifequal %}</p>
            </div>
        </div>

        <div class="panel panel-success">
            <div class="panel-heading">
                <h1 class="panel-title">
                    个人信息
                </h1>
                <a id="edit_corner" href="javascript:void(0)" class="pull-right" style="margin-top: -17px">编辑</a>
            </div>
            <div class="panel-body">

                <div id="noma">
                    <p>学校：<span id="user-school">{{ user.school }}</span></p>

                    <p>专业：<span id="user-major">{{ user.major }}</span></p>

                    <p>姓名：<span id="user-name">{{ user.name }}</span></p>

                    <p>邮箱：<span id="user-email">{{ user.email }}</span></p>

                    <p>地址：<span id="user-address">{{ user.address }}</span></p>
                </div>

                <form id="edit_form" action="javascript:edit_ajax()" hidden="hidden">
                    <p>学校：<input type="text" id="school" value="{{ user.school }}"/></p>

                    <p>专业：<input type="text" id="major" value="{{ user.major }}"/></p>

                    <p>姓名：<input type="text" id="name" value="{{ user.name }}"/></p>

                    <p>邮箱：<input type="text" id="email" value="{{ user.email }}"/></p>

                    <p>地址：<input type="text" id="address" value="{{ user.address }}"/></p>
                    <button type="submit" class="btn btn-success btn-block center-block" role="button"
                            style="width: 100px;">修改
                    </button>
                </form>

            </div>
        </div>
    </div>
</div>


<!-- jQuery (necessary for Bootstrap's JavaScript plugins)-->
<script src="{% static 'bug_vote/js/jquery.min.js' %}"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="{% static 'bug_vote/js/bootstrap.min.js' %}"></script>
<script src="{% static  'bug_vote/js/csrf_ajax.js' %}"></script>

<script>
    $(document).ready(function () {
                use_form('#edit_corner');

                function use_form(element) {
                    $(element).on({
                        click: function () {
                            $('#edit_form').show();
                            $('#noma').hide();
                        }
                    });
                }
            }
    );

    function edit_ajax() {
        var name = $('#name').val();
        var school = $('#school').val();
        var email_ele = $('#email');
        var email = email_ele.val();
        var address = $('#address').val();
        var major = $('#major').val();

        var pattern = /^([a-zA-Z0-9_-])+@([a-zA-Z0-9_-]+\.)+[a-zA-Z0-9_-]+/;
        if (!pattern.test(email)) {
            email_ele.focus();
            return;
        }

        $.post('/api/edit_user/', {
            name: name,
            school: school,
            email: email,
            address: address,
            major: major
        }, function (result) {
            if (result.is_success) {
                $('#edit_form').hide();
                $('#noma').show();
                $('#head_name').text(name);
                $('#user-name').text(name);
                $('#user-school').text(school);
                $('#user-email').text(email);
                $('#user-address').text(address);
                $('#user-major').text(major);
            }
        })
    }

</script>
{% include 'footer.html' %}
</body>
</html>

templates/submit.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    {% load staticfiles %}
    <title>提交bug</title>

    {% include "html_head.html" %}

    <style>
        .navbar {
            margin-bottom: 0px;
            border-radius: 0px;
        }

        .jumbotron {
            height: 50px;
            /*background-attachment:fixed;*/
            background: no-repeat 0 -400px;
            background-size: 100%;
        }

        .reg-box {
            width: 390px;
        }

        .form-group {
            position: relative;
        }

        .form-group span {
            position: absolute;
            left: 370px;
            top: 15px;
        }

        .visible-xs {
            font-size: 40px;
            text-align: center;
        }

        .form-group {
            padding: 6px;
        }

        .reg-head {
            width: 600px;
            padding: 30px 0;
            position: relative;

        }

        .register-font {
            font-size: 40px;
            text-align: center;
            position: absolute;
            left: 200px;
            top: 20px;
            width: 180px;
            background-color: #FFF;;
        }

        .control-label {
            font-size: 16px;
        }
    </style>
</head>
<body>
<!-- Fixed navbar -->
{% include "head.html" %}

<div class="container">
    <div class="page-header">
        <h1>BUG提交</h1>
    </div>
    <form class="form-horizontal" method="post" action="javascript:submit_ajax()">

        <div id="warn_msg" class="form-group alert alert-danger hide"></div>

        <div class="form-group">
            <label for="content-bug" class="col-sm-2 control-label">BUG提交内容</label>

            <div class="col-sm-8">
                <textarea class="form-control" id="content-bug" rows="4"></textarea>
            </div>
        </div>
        <div class="form-group">
            <label for="select-bug" class="col-sm-2 control-label">请选择BUG类型</label>

            <div class="col-sm-4">
                <select class="form-control" id="select-bug">
                    {% for type in type_list %}
                        <option value="{{ type.id }}">{{ type }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-success btn-lg" style="width: 15%">提交</button>
            </div>
        </div>
    </form>
</div>

<script src="{% static 'bug_vote/js/jquery.min.js' %}"></script>
<script src="{% static  'bug_vote/js/csrf_ajax.js' %}"></script>
<script language="JavaScript">
    function submit_ajax() {
        var information = $('#content-bug').val();
        var select_type = $("#select-bug").val();
        if (information == "") {
            var ele = $("#warn_msg");
            ele.removeClass("hide");
            ele.text("提交内容不可为空");
            return;
        }

        $.post("/api/submit_bug/", {
                    information: information,
                    bug_type: select_type
                }, function (result) {
                    if (result.is_success) {
                        location.href = "/person/";
                    } else {
                        var ele = $("#warn_msg");
                        ele.removeClass("hide");
                        ele.text(JSON.stringify(result.msg));
                        return;
                    }
                }
        )
    }
</script>

{% include 'footer.html' %}


</body>
</html>

templates/user_rank.html
<html lang="zh-CN">
<head>
    {% load staticfiles %}
    {% include 'html_head.html' %}
<body>
{% include 'head.html' %}
<div class="container">
    <div class="page-header">
        <h1>比赛排名</h1>
    </div>

    <table class="table table-hover table-striped">
        <thead>
        <tr>
            <th>排名</th>
            <th>名字</th>
            <th>学校</th>
            <th>奖金</th>
            <th>bug数量</th>
        </tr>
        </thead>
        <tbody>
        {% for i,rank in rank_list.items %}
            <tr>
                <td>{{ i }}</td>
                <td>{{ rank.name }}</td>
                <td>{{ rank.school }}</td>
                <td>{{ rank.bonus }}</td>
                <td>{{ rank.bug_number }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

</div>

{% include 'footer.html' %}
</body>
</html>